substitutions:
  # Change device name to match your desired name
  device_name: room-presence-sensor
  # Change sensor name below to the one you want to see in Home Assistant
  device_name_pretty: Room Presence Sensor
  # mmWave RX Pin
  uart_tx_pin: GPIO43
  # mmWave TX Pin
  uart_rx_pin: GPIO44
  # mmWave IO2 Pin
  gpio_pin: GPIO1

# Include the yml file with the sensor configuration
packages:
  inclusions: !include packages/leapmmw_sensor.yml

esphome:
  name: $device_name
  friendly_name: $device_name_pretty

esp32:
  board: esp32-s3-devkitc-1

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

# Connect to WiFi & create captive portal and web server
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name_pretty}"
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80
  version: 2
  include_internal: true

http_request:
  useragent: esphome/$device_name
  timeout: 2s
